# syntax=docker/dockerfile:1.7
#
# CPU image — Ubuntu 22.04 + CPU PyTorch + nemo_toolkit[asr] + faster-whisper +
# kokoro (TTS). Serves whisper variants + canary-180m-flash on CPU for ASR
# (parakeet/1b-flash/qwen-2.5b need GPU and live in Dockerfile.cuda), plus
# kokoro-82m TTS via /v1/audio/speech.
#
# Supply chain:
#   Lightweight runtime deps: uv sync --frozen from uv.lock (hash-verified).
#   Heavy ML stack: uv pip install --require-hashes from requirements-heavy-cpu.txt
#   (generated by scripts/compile-heavy-deps.sh — run `make compile-heavy` to refresh).

FROM python:3.12-slim-bookworm@sha256:d193c6f51a7dbd10395d6328de3a7edb0516fb0608ca138036576f574c3e07d2 AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.15@sha256:e590846f4776907b254ac0f44b5b380347af5d90d668138ca7938d1b0c2f98d3 /uv /usr/local/bin/uv

WORKDIR /app

# 1) Lightweight runtime deps (fastapi, uvicorn, pydantic, python-multipart).
#    Installed from uv.lock — frozen, hash-verified, no re-resolve.
COPY pyproject.toml uv.lock ./
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv /opt/venv && \
    uv sync --frozen --no-dev

# 2) Heavy ML deps — CPU torch + nemo_toolkit[asr]. Hash-locked.
#    See scripts/heavy-deps-cpu.in for version rationale + open-CVE threat model.
COPY requirements-heavy-cpu.txt ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/venv/bin/python \
        --require-hashes \
        --no-deps \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        --index-strategy unsafe-best-match \
        -r requirements-heavy-cpu.txt

# -----------------------------------------------------------------------------
FROM python:3.12-slim-bookworm@sha256:d193c6f51a7dbd10395d6328de3a7edb0516fb0608ca138036576f574c3e07d2 AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/opt/venv/bin:$PATH" \
    PYTHONPATH=/app/src \
    TZ=UTC \
    TALKIES_DEVICE=cpu \
    TALKIES_MODELS_FILE=/app/models.json \
    TALKIES_DATA_DIR=/data \
    HF_HUB_OFFLINE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        ffmpeg \
        libsndfile1 \
        libgomp1 \
        espeak-ng \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -u 1000 --create-home --shell /bin/bash talkies \
    && mkdir -p /data \
    && chown talkies:talkies /data

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
COPY --chown=talkies:talkies src ./src
COPY --chown=talkies:talkies pyproject.toml ./
COPY --chown=talkies:talkies models-cpu.json /app/models.json
COPY --chown=talkies:talkies entrypoint.sh /usr/local/bin/talkies-entrypoint
RUN chmod +x /usr/local/bin/talkies-entrypoint

USER talkies

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD python -c "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz').status==200 else 1)" || exit 1

ENTRYPOINT ["/usr/local/bin/talkies-entrypoint"]
